import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :one_click_campaign, OneClickCampaignWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: OneClickCampaign.Finch

# Do not print debug messages in production
config :logger, level: :info

config :one_click_campaign, ai_chat_service: ExOpenAI.Chat
# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :ex_openai,
  api_key: System.get_env("OPEN_API_KEY"),
  organization_key: System.get_env("ORGANIZATION_KEY"),
  http_options: [recv_timeout: 30_000]
